// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trello.Api.Database;

#nullable disable

namespace Trello.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240519173105_ColumnTemplatesData")]
    partial class ColumnTemplatesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trello.Api.Models.Column", b =>
                {
                    b.Property<int>("ColumnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColumnID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColumnID");

                    b.ToTable("Columns");

                    b.HasData(
                        new
                        {
                            ColumnID = 1,
                            Name = "TODO"
                        },
                        new
                        {
                            ColumnID = 2,
                            Name = "In progress"
                        },
                        new
                        {
                            ColumnID = 3,
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("Trello.Api.Models.ColumnTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("TID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ColumnTemplates");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CID = 1,
                            TID = 1
                        },
                        new
                        {
                            ID = 2,
                            CID = 2,
                            TID = 1
                        },
                        new
                        {
                            ID = 3,
                            CID = 3,
                            TID = 1
                        });
                });

            modelBuilder.Entity("Trello.Api.Models.Template", b =>
                {
                    b.Property<int>("TemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateID");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            TemplateID = 1,
                            Name = "Default"
                        });
                });

            modelBuilder.Entity("Trello.Api.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
